services:
  frontend:
    build: .
    container_name: nextjs_app
    ports:
      - "${NEXT_HOST_PORT}:${NEXT_HOST_PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
