version: "3.8"
services:
  backend:
    build: ./backend
    container_name: fastapi_app
    command: poetry run uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/taskmanager
      - CORS_ORIGINS=http://localhost:3000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=taskmanager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  test:
    build: ./backend
    command: poetry run pytest tests/ -v
    volumes:
      - ./backend:/code
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/taskmanager
    depends_on:
      - db

volumes:
  postgres_data:
