services:
  frontend:
    extends:
      file: ./frontend/docker-compose.yml
      service: frontend
    depends_on:
      - backend

  backend:
    extends:
      file: ./backend/docker-compose.yml
      service: backend
    depends_on:
      - db

  db:
    extends:
      file: ./backend/docker-compose.yml
      service: db

volumes:
  postgres_data:
