services:
  db:
    image: postgres:15
    container_name: postgres_db_test
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${DATABASE_PORT_TEST}:${DATABASE_PORT_TEST}"
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  test:
    build: .
    command: poetry run pytest tests/ -v
    volumes:
      - .:/code
    environment:
      - DATABASE_URL_TEST=${DATABASE_URL_TEST}
    depends_on:
      - db

volumes:
  postgres_data_test:
