services:
  backend:
    build: .
    container_name: fastapi_app
    command: poetry run uvicorn api.main:app --host 0.0.0.0 --port ${TASK_SERVICE_PORT} --reload
    volumes:
      - .:/code
    ports:
      - "${TASK_SERVICE_PORT}:${TASK_SERVICE_PORT}"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - AUTH_SECRET_KEY=${AUTH_SECRET_KEY}
      - AUTH_ALGORITHM=${AUTH_ALGORITHM}
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
